# Generated by Django 4.0.2 on 2022-02-17 11:01

import addressbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Addressbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_line_1", models.CharField(max_length=100)),
                ("address_line_2", models.CharField(default="", max_length=100)),
                ("country", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=50)),
                (
                    "postcode",
                    models.CharField(
                        max_length=50, validators=[addressbook.models.func]
                    ),
                ),
            ],
        ),
    ]
