# Generated by Django 4.0.2 on 2022-02-17 15:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressbook",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
