# Generated by Django 4.0.2 on 2022-02-17 15:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0003_alter_addressbook_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressbook",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
