# Generated by Django 4.0.2 on 2022-02-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0010_alter_addressbook_country_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="addressbook",
            unique_together=set(),
        ),
    ]
