# Generated by Django 4.0.2 on 2022-02-18 08:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("addressbook", "0011_alter_addressbook_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="addressbook",
            unique_together={
                (
                    "owner",
                    "address_line_1",
                    "address_line_2",
                    "country",
                    "city",
                    "postcode",
                )
            },
        ),
    ]
