# Generated by Django 4.0.2 on 2022-02-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0012_alter_addressbook_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="addressbook",
            unique_together=set(),
        ),
    ]
